esphome:
  name: ir-remote-control
  friendly_name: IR Remote Control

bk72xx:
  board: generic-bk7231n-qfn32-tuya
  
# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

# Allow Over-The-Air updates
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret fallback_hotspot_password

captive_portal:

output:
  - platform: libretiny_pwm
    id: led
    pin: 24

light:
  - platform: monochromatic
    id: led_light
    output: led

binary_sensor:
  - platform: gpio
    id: btn
    pin:
      number: 9
      mode:
        input: true
        pullup: true
      inverted: true

remote_transmitter:
  pin: 7
  carrier_duty_percent: 50%

remote_receiver:
  pin:
    number: 8
    inverted: true
    mode:
      input: true
      pullup: true
  on_sony: 
    - lambda: |-
        ESP_LOGI("sony_ir", "Received Sony → data=0x%X, nbits=%u", x.data, x.nbits);

button:
  - platform: template
    name: "Power Toggle"
    on_press:
      - remote_transmitter.transmit_sony:
          data: 0xA90
          nbits: 12
          repeat:
            times: 5
            wait_time: 40ms

  - platform: template
    name: "Power On"
    on_press:
      - remote_transmitter.transmit_sony:
          data: 0x750
          nbits: 12
          repeat:
            times: 5
            wait_time: 40ms

  - platform: template
    name: "Power Off"
    on_press:
      - remote_transmitter.transmit_sony:
          data: 0xF50
          nbits: 12
          repeat:
            times: 5
            wait_time: 40ms

  - platform: template
    name: "Home"
    on_press:
      - remote_transmitter.transmit_sony:
          data: 0x070
          nbits: 12
          repeat:
            times: 3
            wait_time: 40ms

  - platform: template
    name: "Up"
    on_press:
      - remote_transmitter.transmit_sony:
          data: 0x2F0
          nbits: 12
          repeat:
            times: 2
            wait_time: 25ms

  - platform: template
    name: "Down"
    on_press:
      - remote_transmitter.transmit_sony:
          data: 0xAF0
          nbits: 12
          repeat:
            times: 2
            wait_time: 25ms

  - platform: template
    name: "Left"
    on_press:
      - remote_transmitter.transmit_sony:
          data: 0x2D0
          nbits: 12
          repeat:
            times: 2
            wait_time: 25ms

  - platform: template
    name: "Right"
    on_press:
      - remote_transmitter.transmit_sony:
          data: 0xCD0
          nbits: 12
          repeat:
            times: 2
            wait_time: 25ms

  - platform: template
    name: "OK"
    on_press:
      - remote_transmitter.transmit_sony:
          data: 0xA70
          nbits: 12
          repeat:
            times: 3
            wait_time: 40ms

  - platform: template
    name: "YouTube"
    on_press:
      - remote_transmitter.transmit_sony:
          data: 0x7123
          nbits: 15
          repeat:
            times: 3
            wait_time: 40ms
